type separator =
  | Dot [@printer fun fmt _ -> fprintf fmt "."]
  | DotDotDot [@printer fun fmt _ -> fprintf fmt "..."]
  | Comma [@printer fun fmt _ -> fprintf fmt ","]
  | Colon [@printer fun fmt _ -> fprintf fmt ":"]
  | ColonColon [@printer fun fmt _ -> fprintf fmt "::"]
  | Bar [@printer fun fmt _ -> fprintf fmt "|"]
  | Arrow [@printer fun fmt _ -> fprintf fmt "->"]
  | InverseArrow [@printer fun fmt _ -> fprintf fmt "<-"]
  | FatArrow [@printer fun fmt _ -> fprintf fmt "=>"]
  | At [@printer fun fmt _ -> fprintf fmt "@"]
  | LeftParen [@printer fun fmt _ -> fprintf fmt "("]
  | RightParen [@printer fun fmt _ -> fprintf fmt ")"]
  | LeftBrace [@printer fun fmt _ -> fprintf fmt "{"]
  | RightBrace [@printer fun fmt _ -> fprintf fmt "}"]
  | LeftHook [@printer fun fmt _ -> fprintf fmt "["]
  | RightHook [@printer fun fmt _ -> fprintf fmt "]"]
  | Hashtag [@printer fun fmt _ -> fprintf fmt "#"]
  | Wave [@printer fun fmt _ -> fprintf fmt "~"]
  | Eof [@printer fun fmt _ -> fprintf fmt "EOF"]
[@@deriving show]

type operator =
  | Plus [@printer fun fmt _ -> fprintf fmt "+"]
  | Minus [@printer fun fmt _ -> fprintf fmt "-"]
  | Star [@printer fun fmt _ -> fprintf fmt "*"]
  | Slash [@printer fun fmt _ -> fprintf fmt "/"]
  | Percentage [@printer fun fmt _ -> fprintf fmt "%%"]
  | Hat [@printer fun fmt _ -> fprintf fmt "^"]
  | PlusPlus [@printer fun fmt _ -> fprintf fmt "++"]
  | MinusMinus [@printer fun fmt _ -> fprintf fmt "--"]
  | ColonEq [@printer fun fmt _ -> fprintf fmt ":="]
  | PlusEq [@printer fun fmt _ -> fprintf fmt "+="]
  | MinusEq [@printer fun fmt _ -> fprintf fmt "-="]
  | StarEq [@printer fun fmt _ -> fprintf fmt "*="]
  | SlashEq [@printer fun fmt _ -> fprintf fmt "/="]
  | PercentageEq [@printer fun fmt _ -> fprintf fmt "%%="]
  | HatEq [@printer fun fmt _ -> fprintf fmt "^="]
  | Eq [@printer fun fmt _ -> fprintf fmt "="]
  | EqEq [@printer fun fmt _ -> fprintf fmt "=="]
  | DotDot [@printer fun fmt _ -> fprintf fmt ".."]
  | LeftShift [@printer fun fmt _ -> fprintf fmt "<"]
  | RightShift [@printer fun fmt _ -> fprintf fmt ">"]
  | LeftShiftEq [@printer fun fmt _ -> fprintf fmt "<="]
  | RightShiftEq [@printer fun fmt _ -> fprintf fmt ">="]
  | BangEq [@printer fun fmt _ -> fprintf fmt "!="]
  | Interrogation [@printer fun fmt _ -> fprintf fmt "?"]
  | Ampersand [@printer fun fmt _ -> fprintf fmt "&"]
[@@deriving show]

type keyword =
  | Pub [@printer fun fmt _ -> fprintf fmt "pub"]
  | Self [@printer fun fmt _ -> fprintf fmt "self"]
  | Virtual [@printer fun fmt _ -> fprintf fmt "virtual"]
  | Break [@printer fun fmt _ -> fprintf fmt "break"]
  | Next [@printer fun fmt _ -> fprintf fmt "next"]
  | If [@printer fun fmt _ -> fprintf fmt "if"]
  | Elif [@printer fun fmt _ -> fprintf fmt "elif"]
  | Else [@printer fun fmt _ -> fprintf fmt "else"]
  | Match [@printer fun fmt _ -> fprintf fmt "match"]
  | And [@printer fun fmt _ -> fprintf fmt "and"]
  | Or [@printer fun fmt _ -> fprintf fmt "or"]
  | Not [@printer fun fmt _ -> fprintf fmt "not"]
  | While [@printer fun fmt _ -> fprintf fmt "while"]
  | For [@printer fun fmt _ -> fprintf fmt "for"]
  | New [@printer fun fmt _ -> fprintf fmt "new"]
  | Undef [@printer fun fmt _ -> fprintf fmt "undef"]
  | Alias [@printer fun fmt _ -> fprintf fmt "alias"]
  | Record [@printer fun fmt _ -> fprintf fmt "record"]
  | Trait [@printer fun fmt _ -> fprintf fmt "trait"]
  | Enum [@printer fun fmt _ -> fprintf fmt "enum"]
  | Fun [@printer fun fmt _ -> fprintf fmt "fun"]
  | End [@printer fun fmt _ -> fprintf fmt "end"]
  | In [@printer fun fmt _ -> fprintf fmt "in"]
  | Import [@printer fun fmt _ -> fprintf fmt "import"]
  | Class [@printer fun fmt _ -> fprintf fmt "class"]
  | Try [@printer fun fmt _ -> fprintf fmt "try"]
  | Catch [@printer fun fmt _ -> fprintf fmt "catch"]
  | Type [@printer fun fmt _ -> fprintf fmt "type"]
  | Object [@printer fun fmt _ -> fprintf fmt "object"]
  | Async [@printer fun fmt _ -> fprintf fmt "async"]
  | Await [@printer fun fmt _ -> fprintf fmt "await"]
  | Module [@printer fun fmt _ -> fprintf fmt "module"]
  | As [@printer fun fmt _ -> fprintf fmt "as"]
  | Do [@printer fun fmt _ -> fprintf fmt "do"]
  | Include [@printer fun fmt _ -> fprintf fmt "include"]
  | Macro [@printer fun fmt _ -> fprintf fmt "macro"]
  | Test [@printer fun fmt _ -> fprintf fmt "test"]
  | True [@printer fun fmt _ -> fprintf fmt "True"]
  | False [@printer fun fmt _ -> fprintf fmt "False"]
  | Return [@printer fun fmt _ -> fprintf fmt "return"]
  | Char [@printer fun fmt _ -> fprintf fmt "Char"]
  | Int8 [@printer fun fmt _ -> fprintf fmt "Int8"]
  | Int16 [@printer fun fmt _ -> fprintf fmt "Int16"]
  | Int32 [@printer fun fmt _ -> fprintf fmt "Int32"]
  | Int64 [@printer fun fmt _ -> fprintf fmt "Int64"]
  | Uint8 [@printer fun fmt _ -> fprintf fmt "Uint8"]
  | Uint16 [@printer fun fmt _ -> fprintf fmt "Uint16"]
  | Uint32 [@printer fun fmt _ -> fprintf fmt "Uint32"]
  | Uint64 [@printer fun fmt _ -> fprintf fmt "Uint64"]
  | Float32 [@printer fun fmt _ -> fprintf fmt "Float32"]
  | Float64 [@printer fun fmt _ -> fprintf fmt "Float64"]
  | String [@printer fun fmt _ -> fprintf fmt "String"]
  | Usize [@printer fun fmt _ -> fprintf fmt "Usize"]
  | Isize [@printer fun fmt _ -> fprintf fmt "Isize"]
  | Bool [@printer fun fmt _ -> fprintf fmt "Bool"]
  | Unit [@printer fun fmt _ -> fprintf fmt "Unit"]
  | Nil [@printer fun fmt _ -> fprintf fmt "nil"]
  | Mut [@printer fun fmt _ -> fprintf fmt "mut"]
[@@deriving show]

type literal =
  | String of string [@printer fun fmt s -> fprintf fmt "\"%s\"" s]
  | Char of char [@printer fun fmt c -> fprintf fmt "\'%c\'" c]
  | Float of string [@printer fun fmt f -> fprintf fmt "%s" f]
  | Int of string [@printer fun fmt i -> fprintf fmt "%s" i]
[@@deriving show]

type comment =
  | One [@printer fun fmt _ -> fprintf fmt "One"]
  | Multi [@printer fun fmt _ -> fprintf fmt "Multi"]
  | Doc of string [@printer fun fmt s -> fprintf fmt "Doc: %s" s]
[@@deriving show]

type token =
  | Separator of separator
      [@printer fun fmt s -> fprintf fmt "%s" (show_separator s)]
  | Operator of operator
      [@printer fun fmt o -> fprintf fmt "%s" (show_operator o)]
  | Keyword of keyword
      [@printer fun fmt k -> fprintf fmt "%s" (show_keyword k)]
  | Identifier of string
      [@printer fun fmt s -> fprintf fmt "%s" s]
  | Literal of literal
      [@printer fun fmt l -> fprintf fmt "%s" (show_literal l)]
  | Comment of comment
      [@printer fun fmt c -> fprintf fmt "%s" (show_comment c)]
[@@deriving show]
