name: Valid commits

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      ref: ${{ github.event.pull_request.head.sha }}

    - name: Valid commits
      working-directory: ${{github.workspace}}
      run: ./scripts/ci/valid_commits.sh
